version: "3.8"

services:
  ogn-api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY}
    networks:
      - ogn-proxy_ogn
      - default
    restart: always
 #   ports:
#      - 4444:4000
    labels:
      traefik.enable: true
      traefik.http.routers.ogn-api.rule: "Host(`flarm.xccup.net`)"
      traefik.http.routers.ogn-api.entrypoints: websecure
      traefik.http.routers.ogn-api.tls.certresolver: myresolver
      traefik.http.routers.ogn-api.priority: 100
      traefik.port: 4444
      traefik.docker.network: traefik

networks:
  default:
    name: traefik
    external: true

  ogn-proxy_ogn:
    driver: bridge
    external: true
